mv section3/http-server/after.js section3/http-server/after.mjs
mv section3/http-server/after.js section3/http-server/after.mjs
mv section3/http-server/after.js section3/http-server/after.mjs
mv section3/http-server/after.js section3/http-server/after.mjs
mv section3/http-server/after.js section3/http-server/after.mjs
mv section3/http-server/after.js section3/http-server/after.mjs
mv section3/http-server/final.js section3/http-server/final.mjs
mv section3/http-server/final.js section3/http-server/final.mjs
mv section3/http-server/final.js section3/http-server/final.mjs
mv section3/http-server/final.js section3/http-server/final.mjs
mv section3/http-server/final.js section3/http-server/final.mjs
mv section3/http-server/before.js section3/http-server/before.mjs
mv section3/http-server/before.js section3/http-server/before.mjs
mv section3/http-server/before.js section3/http-server/before.mjs
mv section3/http-server/before.js section3/http-server/before.mjs
mv section3/http-server/before.js section3/http-server/before.mjs
mv section3/http-server/before.js section3/http-server/before.mjs
mv section3/http-server/hello_world.js section3/http-server/hello_world.mjs
mv section3/http-server/hello_world.js section3/http-server/hello_world.mjs
mv section3/piscina-stream-in/index.js section3/piscina-stream-in/index.mjs
mv section3/piscina-stream-in/index.js section3/piscina-stream-in/index.mjs
mv section3/piscina-stream-in/index.js section3/piscina-stream-in/index.mjs
mv section3/piscina-stream-in/index.js section3/piscina-stream-in/index.mjs
mv section3/piscina-stream-in/index.js section3/piscina-stream-in/index.mjs
mv section3/piscina-stream-in/progress.js section3/piscina-stream-in/progress.mjs
mv section3/bluebird/example.js section3/bluebird/example.mjs
mv section3/promise-all/second.js section3/promise-all/second.mjs
mv section3/promise-all/second.js section3/promise-all/second.mjs
mv section3/promise-all/third.js section3/promise-all/third.mjs
mv section3/promise-all/third.js section3/promise-all/third.mjs
mv section3/promise-all/third.js section3/promise-all/third.mjs
mv section3/promise-all/first.js section3/promise-all/first.mjs
mv section3/promise-all/first.js section3/promise-all/first.mjs
mv section3/process-race/after.js section3/process-race/after.mjs
mv section3/process-race/before.js section3/process-race/before.mjs
mv section2/stream-error-handling/fixed.js section2/stream-error-handling/fixed.mjs
mv section2/stream-error-handling/better.js section2/stream-error-handling/better.mjs
mv section2/stream-error-handling/broken.js section2/stream-error-handling/broken.mjs
mv section2/caching-promises/fixed.js section2/caching-promises/fixed.mjs
mv section2/caching-promises/fixed.js section2/caching-promises/fixed.mjs
mv section2/caching-promises/broken.js section2/caching-promises/broken.mjs
mv section2/caching-promises/broken.js section2/caching-promises/broken.mjs
mv section2/event-handler-error-handling/fixed.js section2/event-handler-error-handling/fixed.mjs
mv section2/event-handler-error-handling/fixed.js section2/event-handler-error-handling/fixed.mjs
mv section2/event-handler-error-handling/fixed-once.js section2/event-handler-error-handling/fixed-once.mjs
mv section2/event-handler-error-handling/fixed-once.js section2/event-handler-error-handling/fixed-once.mjs
mv section2/event-handler-error-handling/better.js section2/event-handler-error-handling/better.mjs
mv section2/event-handler-error-handling/fixed-better.js section2/event-handler-error-handling/fixed-better.mjs
mv section2/event-handler-error-handling/fixed-better.js section2/event-handler-error-handling/fixed-better.mjs
mv section2/event-handler-error-handling/broken.js section2/event-handler-error-handling/broken.mjs
mv section2/event-handler-error-handling/broken.js section2/event-handler-error-handling/broken.mjs
mv section2/event-handler-error-handling/still-broken.js section2/event-handler-error-handling/still-broken.mjs
mv section2/event-handler-error-handling/still-broken.js section2/event-handler-error-handling/still-broken.mjs
mv section2/event-handler-error-handling/but-still-broken.js section2/event-handler-error-handling/but-still-broken.mjs
mv section2/event-handler-error-handling/but-still-broken.js section2/event-handler-error-handling/but-still-broken.mjs
mv section2/convert-callbacks/after.js section2/convert-callbacks/after.mjs
mv section2/convert-callbacks/after.js section2/convert-callbacks/after.mjs
mv section2/convert-callbacks/after.js section2/convert-callbacks/after.mjs
mv section2/convert-callbacks/after.js section2/convert-callbacks/after.mjs
mv section2/convert-callbacks/after.js section2/convert-callbacks/after.mjs
mv section2/convert-callbacks/after.js section2/convert-callbacks/after.mjs
mv section2/convert-callbacks/after.js section2/convert-callbacks/after.mjs
mv section2/convert-callbacks/before.js section2/convert-callbacks/before.mjs
mv section2/convert-callbacks/before.js section2/convert-callbacks/before.mjs
mv section2/convert-callbacks/before.js section2/convert-callbacks/before.mjs
mv section2/convert-callbacks/before.js section2/convert-callbacks/before.mjs
mv section2/convert-callbacks/before.js section2/convert-callbacks/before.mjs
mv section2/async-callbacks/after.js section2/async-callbacks/after.mjs
mv section2/async-callbacks/after.js section2/async-callbacks/after.mjs
mv section2/async-callbacks/before.js section2/async-callbacks/before.mjs
mv section2/async-callbacks/before.js section2/async-callbacks/before.mjs